name: 'CDK-Deploy'
description: 'A github action to deploy our code on AWS by using CDK'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  cdk_version:
    description: 'aws cdk version'
    required: false
    default: 'latest'
  cdk_stack:
    description: 'cdk stack name'
    required: true
    default: '*'
  cdk_env:
    description: 'cdk environment being released into'
    required: true
    default: '*'
  cdk_action:
    description: 'cdk action example: diff | deploy | synth'
    required: true
    default: 'diff'