name: "CDK-Deploy"
description: "A github action to deploy our code on AWS by using CDK"

inputs:
  cdk_version:
    description: "aws cdk version"
    required: false
    default: "latest"
  cdk_action:
    description: "cdk action example: diff | deploy | synth"
    required: true
  cdk_env:
    description: "cdk environment being released into"
    required: true
  cdk_stack:
    description: "cdk stack name"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: "18.14"
    - run: echo "Env on action.yml:"
      shell: bash
    - run: env
      shell: bash
    - run: echo "DONE Env on action.yml"
      shell: bash
    - run: $GITHUB_ACTION_PATH/deploy.sh
      shell: bash
      env:
        INPUT_CDK_ACTION: ${{ inputs.cdk_action }}
        INPUT_CDK_STACK: ${{ inputs.cdk_stack }}
        INPUT_CDK_ENV: ${{ inputs.cdk_env }}
        INPUT_CDK_VERSION: ${{ inputs.cdk_version }}
        # These are already passed as env vars from the caller
        # AWS_ACCESS_KEY_ID
        # AWS_SECRET_ACCESS_KEY
        # AWS_DEFAULT_REGION

