name: "CDK-Deploy"
description: "A github action to deploy our code on AWS by using CDK"
# runs:
#   using: 'docker'
#   image: 'Dockerfile'
inputs:
  cdk_version:
    description: "aws cdk version"
    required: false
    default: "latest"
  cdk_action:
    description: "cdk action example: diff | deploy | synth"
    required: true
    # default: "diff"
  cdk_env:
    description: "cdk environment being released into"
    required: true
    # default: "*"
  cdk_stack:
    description: "cdk stack name"
    required: true
    # default: "*"
  AWS_ACCESS_KEY_ID:
    description: "the AWS secret id"
    required: true
    # default: "*"
  AWS_SECRET_ACCESS_KEY:
    description: "the AWS secret key"
    required: true
    # default: "*"
  AWS_DEFAULT_REGION:
    description: "the AWS region we're deploying to"
    required: true
    # default: "*"

runs:
  using: "composite"
  # env:
  #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #   AWS_DEFAULT_REGION: "${{ inputs.aws_region }}"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: "16"
    - run: echo "Env on action.yml:"
      shell: bash
    - run: env
      shell: bash
    - run: echo "DONE Env on action.yml"
      shell: bash
    - run: $GITHUB_ACTION_PATH/deploy.sh
      shell: bash
      env:
        INPUT_CDK_ACTION: ${{ inputs.cdk_action }}
        INPUT_CDK_STACK: ${{ inputs.cdk_stack }}
        INPUT_CDK_ENV: ${{ inputs.cdk_env }}
        INPUT_CDK_VERSION: ${{ inputs.cdk_version }}
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ inputs.AWS_DEFAULT_REGION }}

